name: Benchmark and Plot Results

on:
  pull_request:
  workflow_dispatch:
#  schedule:
#    # Run benchmarks daily at 2 AM UTC
#    - cron: '0 2 * * *'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Run benchmarks
      run: |
        # Create output directory
        mkdir -p benchmark-results
        
        # Run benchmarks and save raw output
        go test -bench=. -benchmem -count=3 -timeout=30m > benchmark-results/raw_output.txt
        
        # Also save in a more parseable format
        go test -bench=. -benchmem -count=3 -timeout=30m | tee benchmark-results/benchmark_output.txt
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas numpy seaborn
        
    - name: Parse and plot benchmark results
      run: |
        python scripts/plot_benchmarks.py
        
    - name: Upload benchmark plots
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-plots-${{ github.sha }}
        path: benchmark-results/plots/
        
    - name: Store benchmark history
      if: github.ref == 'refs/heads/main'
      run: |
        # Create or update benchmark history
        python scripts/update_benchmark_history.py
        
    - name: Commit benchmark results
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add benchmark-results/history/
        git diff --staged --quiet || git commit -m "Update benchmark results [skip ci]"
        git push
        
    - name: Comment on PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Read benchmark summary
          const summaryPath = 'benchmark-results/summary.md';
          if (fs.existsSync(summaryPath)) {
            const summary = fs.readFileSync(summaryPath, 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📊 Benchmark Results\n\n${summary}`
            });
          }
          
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./benchmark-results/plots/
        destination_dir: benchmarks